language: rust
sudo: false

cache: cargo

os:
    - linux
    - osx

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo bench;
    fi


script:
    - cargo build --verbose
    - cargo test --verbose
