[package]
name = "dehex"
version = "0.1.0"
authors = ["Ulf Ejlertsson <ulf.ejlertsson@gmail.com>"]


[badges]
travis-ci = { repository = "stormogulen/dehex" }

[dependencies]
gl = "0.10.0"

[dependencies.sdl2]
version = "0.31.0"
features = ["bundled", "static-link"]
